<?php

// =============================================================================
// FILE: includes/class-email-handler.php
// =============================================================================

/**
 * Email functionality for sending reports
 */
class UK_Mortgage_Email_Handler {
    
    public function send_calculation_report($email, $calculator_type, $inputs, $results) {
        $subject = 'Your ' . ucfirst($calculator_type) . ' Calculation Report';
        $message = $this->generate_email_content($calculator_type, $inputs, $results);
        
        $headers = [
            'Content-Type: text/html; charset=UTF-8',
            'From: ' . get_bloginfo('name') . ' <' . get_option('admin_email') . '>'
        ];
        
        return wp_mail($email, $subject, $message, $headers);
    }
    
    private function generate_email_content($calculator_type, $inputs, $results) {
        ob_start();
        ?>
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <style>
                body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
                .container { max-width: 600px; margin: 0 auto; padding: 20px; }
                .header { background: #007cba; color: white; padding: 20px; text-align: center; }
                .content { padding: 20px; background: #f9f9f9; }
                .result { background: white; padding: 15px; margin: 10px 0; border-left: 4px solid #007cba; }
                .footer { text-align: center; padding: 20px; font-size: 12px; color: #666; }
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1><?php echo ucfirst($calculator_type); ?> Calculation Report</h1>
                </div>
                <div class="content">
                    <?php $this->render_email_results($calculator_type, $inputs, $results); ?>
                </div>
                <div class="footer">
                    <p>This report was generated by <?php echo get_bloginfo('name'); ?></p>
                    <p>Please consult with a qualified mortgage advisor for personalized advice.</p>
                </div>
            </div>
        </body>
        </html>
        <?php
        return ob_get_clean();
    }
    
    private function render_email_results($calculator_type, $inputs, $results) {
        switch ($calculator_type) {
            case 'affordability':
                ?>
                <div class="result">
                    <h3>Maximum Borrowing: £<?php echo number_format($results['max_borrowing']); ?></h3>
                    <p>Based on your income of £<?php echo number_format($inputs['annual_income']); ?> and deposit of £<?php echo number_format($inputs['deposit']); ?></p>
                </div>
                <div class="result">
                    <h3>Maximum Property Value: £<?php echo number_format($results['max_property_value']); ?></h3>
                    <p>Including your deposit, you could afford a property worth up to this amount.</p>
                </div>
                <?php
                break;
                
            case 'repayment':
                ?>
                <div class="result">
                    <h3>Monthly Payment: £<?php echo number_format($results['monthly_payment'], 2); ?></h3>
                    <p>For a loan of £<?php echo number_format($inputs['loan_amount']); ?> at <?php echo $inputs['interest_rate']; ?>% over <?php echo $inputs['term_years']; ?> years</p>
                </div>
                <?php
                break;
        }
    }
}
